# Generated by Django 6.0.1 on 2026-02-04 14:42

from django.db import migrations, models


def clean_duplicate_phone_numbers(apps, schema_editor):
    """Clear phone_number for duplicate active users so unique constraint can apply."""
    User = apps.get_model('sonic_app', 'User')
    from django.db.models import Q
    active = User.objects.filter(is_delete=False).exclude(
        Q(phone_number__isnull=True) | Q(phone_number='')
    )
    seen = set()
    for user in active.order_by('id'):
        phone = user.phone_number
        if phone in seen:
            user.phone_number = ''
            user.save(update_fields=['phone_number'])
        else:
            seen.add(phone)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sonic_app', '0004_session_address_session_latitude_session_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='auth_token',
            field=models.CharField(blank=True, help_text='Bearer token for mobile API auth', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, help_text='Phone number verified via OTP'),
        ),
        migrations.RunPython(clean_duplicate_phone_numbers, noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False), ('phone_number__isnull', False), models.Q(('phone_number', ''), _negated=True)), fields=('phone_number',), name='unique_phone_per_active_user'),
        ),
    ]
