# Generated by Django - add product_weight to Product

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonic_app', '0007_product_variant_and_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_weight',
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text='Weight (required for new products)',
                max_digits=10,
                null=True,
            ),
        ),
    ]
