# Generated by Django 5.2.11 on 2026-02-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonic_app', '0008_add_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfield',
            name='is_variant_dimension',
            field=models.BooleanField(default=False, help_text='Use as variant dimension (e.g. Size, Karat)'),
        ),
        migrations.AlterField(
            model_name='categoryfield',
            name='variant_order',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Order of this variant dimension (1, 2, 3, ...)', null=True),
        ),
    ]
