# Generated by Django 6.0.1 on 2026-02-15 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonic_app', '0009_alter_categoryfield_is_variant_dimension_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gst', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='sonic_app.product')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Lead',
                'verbose_name_plural': 'Product Leads',
                'db_table': 'sonic_app_product_lead',
                'ordering': ['-created_at'],
            },
        ),
    ]
